spring:
    http:
        encoding:
            charset: UTF-8
    output:
        ansi:
            enabled: always
    mvc:
        static-path-pattern: /static/**
    resources:
        add-mappings: 'true'
        static-locations: classpath:/static/
server:
    port: 8888
    tomcat:
        uri-encoding: UTF-8
    
   
    